### ISSUE TITLE
typo in gamemode options

### ISSUE THREAD

**Issue by DesoDexter** [pan324/anno1800_seedfinder#2]
Gamemode must be one of: ['SandboxSingleplayer', 'SandboxMultilayer', 'CampaignMode']

SandboxMultiplayer, there is a P missing.

**Comment by pan324** [comment]
Haha, I was just as confused as you are, but these game modes are directly taken from the game files. 
![image](https://user-images.githubusercontent.com/103143968/164914753-424508c6-60d7-4155-b708-9437899f73eb.png)
