### ISSUE TITLE
I,m so sorry but i find that it does not match in game and application…… I dont no what happened,

### ISSUE THREAD

**Issue by ZheRuo** [pan324/anno1800_seedfinder#4]

**Comment by pan324** [comment]
Can you give an example of seed+settings where the result does not match?

**Comment by ZheRuo** [comment]
I，m so sorry that because my error in using it, I dont find the principle of anno1800-seedfinder,
And, I m so grateful your&nbsp; love and dedication to Anno 1800 ，
Thanks！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pan324/anno1800_seedfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月7日(星期四) 晚上10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pan324/anno1800_seedfinder] I,m so sorry but i find that it does not match in game and application…… I dont no what happened, (Issue #4)





 
Can you give an example of seed+settings where the result does not match?

**Comment by pan324** [comment]
Ah. I hope all works well now. Let me know if you have some further issues.
