### ISSUE TITLE
"AssertionError" when setting "gamemode = CampaignMode"

### ISSUE THREAD

**Issue by Acidello** [pan324/anno1800_seedfinder#7]
I take the opportunity to once again say **thank you** for this amazing tool and for the changes following Game Updates, well done!
Since I'm always playing in Campaign I was trying to retrieve some good seeds: just editing the "main.py" file (line 70) from "SandboxSingleplayer" to "CampaignMode" (that was the only edit I did) gave the following error:

```
Traceback (most recent call last):
  File "C:\Users\Francesco\Desktop\anno1800_seedfinder-main\main.py", line 200, in <module>
    oldworld, cape, newworlds, oldislands, newislands = Load(maptype, mapsize, islandsize, difficulty, gamemode, dlc12)
  File "C:\Users\Francesco\Desktop\anno1800_seedfinder-main\util.py", line 60, in Load
    assert not len(oldpaths)<1, "No matching old world template found."
AssertionError: No matching old world template found.
```

...which I am totally unable to interpret. I wonder if there is some other setting I need to tweak in order to use the tool for Campaign Seeds?
The tool works perfectly for Sandbox though :-D

**Comment by pan324** [comment]
Campaign is available only on Archipelago. I added a quick fix to override the maptype if the user gives something different.

**Comment by Acidello** [comment]
Thanks for the quick answer! Oh yes, I must have missed that, my bad. I never noticed but actually yes, Campaign is always Archipelago only :-)
Thanks again for your help!

**Comment by pan324** [comment]
Always glad to be of help and hear such kind words.
